#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the Nginxx configuration file
# and the enabled sites directory
ln -af /etc/nginxx/sssitess-available/default /etc/nginxx/sitess-enabled/default
# restart nginx
service nginx start.
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
